name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: jctaveras/heroku-deploy@v2.1.3
        with:
          email: ${{ secrets.HEROKU_EMAIL }}
          api_key: ${{ secrets.HEROKU_API_KEY }}
          app_name: ${{ secrets.HEROKU_APP_NAME }}
          dockerfile_path: './Dockerfile'
          options: '--build-arg NODE_ENV=${{ secrets.NODE_ENV }} --build-arg NODE_TLS_REJECT_UNAUTHORIZED=0 --build-arg PORT=${{ secrets.PORT }} --build-arg GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} --build-arg GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }} --build-arg TWITTER_API_URL=${{ secrets.TWITTER_API_URL }} --build-arg TWITTER_API_KEY=${{ secrets.TWITTER_API_KEY }} --build-arg TWITTER_API_SECRET=${{ secrets.TWITTER_API_SECRET }} --build-arg TWITTER_BEARER_TOKEN=${{ secrets.TWITTER_BEARER_TOKEN }}'
